### PR TITLE
Fix hmr not working

### PR DESCRIPTION
**Pull request by a145789**

### CODE REVIEW

**Comment by a145789** [comment]
hello, HMR still does not work in the latest updated version, I try to upgrade vite version, I tried to upgrade the Vite version to the latest, hmr is normal. Maybe try this way.
 Thanks for you plugin.

**Comment by jihchi** [comment]
It seems like consumers just upgrade their version of Vite and it works.

I think this is nothing to do with the plugin.

**Comment by jihchi** [comment]
I'm not sure it is relevant to the plugin, could you please elaborate it?

**Comment by a145789** [comment]
yes, the question is .bsb.lock, I don't know why this file is not banned from uploading, and is not being updated by rescript, i delete it, everything is normal.

**Pull request closed without merging**
