### PR TITLE
Update npm deps

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Review by jihchi — APPROVED** [review]
Looks good to me!

Thank you!

**Comment by smorimoto** [comment]
It seems that publishing the npm package is...

```log
xxx:build: import execa from "execa";
xxx:build:        ^^^^^
xxx:build: SyntaxError: The requested module 'execa' does not provide an export named 'default'
```

**Comment by smorimoto** [comment]
@jihchi Did you probably publish it before installing (and building the package) deps?

**Comment by smorimoto** [comment]
https://github.com/smorimoto/rescript-vercel-speed-insights-example/actions/runs/8588062284/job/23532440185?pr=10

**Comment by smorimoto** [comment]
`5.6.1` works!

**Comment by jihchi** [comment]
@smorimoto Sorry for the inconvenience. `v5.6.0` was staled.

**Pull request merged**
